#!/bin/bash
    echo -e "\033[1;34m[\033[1;37m01\033[1;34m] \033[1;37m• \033[1;33mCRIAR USUARIO"
    echo -e "\033[1;34m [\033[1;37mV \033[1;34m] \033[1;37m• \033[1;33mV2RAY $xv2ray
    \033[0;37m╠━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━\033[0m 
	\033[1;37m╰━━━━━━━━❪\033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m"
	case "$x" in 
   1 | 01)
   clear
   utilite
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
    v | V) 
    v2raymanager
    ;;
    esac
		done
	}
	fun_conexao
}
